# CHANGE THIS TO YOUR OWN DATASET
TTS_dataset: "kadirnar/Stephen_Fry-tokenized-granite"

model_name: "Vyvo/VyvoTTS-Granite-1B-PT"

# Training Args
epochs: 1
batch_size: 16
number_processes: 1
pad_token: 100256  # Granite's PAD token
save_steps: 5000
learning_rate: 5.0e-5

# Naming and paths
save_folder: "checkpoints"
project_name: "tuning-vyvotts-granite"
run_name: "5e5-0"
