TOKENIZER_LENGTH: 100352
START_OF_TEXT: 100257  # BOS token (same as EOS in Granite)
END_OF_TEXT: 100257    # EOS token
START_OF_SPEECH: 100353  # TOKENIZER_LENGTH + 1
END_OF_SPEECH: 100354    # TOKENIZER_LENGTH + 2
START_OF_HUMAN: 100355   # TOKENIZER_LENGTH + 3
END_OF_HUMAN: 100356     # TOKENIZER_LENGTH + 4
START_OF_AI: 100357      # TOKENIZER_LENGTH + 5
END_OF_AI: 100358        # TOKENIZER_LENGTH + 6
PAD_TOKEN: 100256        # Granite's native PAD token
AUDIO_TOKENS_START: 100361  # TOKENIZER_LENGTH + 10
