TOKENIZER_LENGTH: 128256
START_OF_TEXT: 128000
END_OF_TEXT: 128009
START_OF_SPEECH: 128257  # TOKENIZER_LENGTH + 1
END_OF_SPEECH: 128258    # TOKENIZER_LENGTH + 2
START_OF_HUMAN: 128259   # TOKENIZER_LENGTH + 3
END_OF_HUMAN: 128260     # TOKENIZER_LENGTH + 4
START_OF_AI: 128261      # TOKENIZER_LENGTH + 5
END_OF_AI: 128262        # TOKENIZER_LENGTH + 6
PAD_TOKEN: 128263        # TOKENIZER_LENGTH + 7
AUDIO_TOKENS_START: 128266  # TOKENIZER_LENGTH + 10
